language: node_js
node_js: '8.10'

script: npm run test && npm run coverage

deploy:
  # Indonesia Prod Detik Lambda
  - provider: lambda
    function_name: "cognicity-reports-detik-dev"
    region: $AWS_REGION_ID
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/detik/index"
    handler_name: "default"
    on:
      branch: dev
